repository: git@github.com:germantech/chamados.git 
 
#repository: https://victormbalves:V1i5c0t7o9r8@github.com/germantech/chamados.git
platforms:
    development:
        default_branch: master-dev
        max_releases: 3
        servers:
            dev:
                host: localhost
                user: root
                #ssh_key: /machine/private_key
                password: vagrant
                path: /var/www/html/testechamados
                port: 22
    production:
        default_branch: master
        max_releases: 3
        servers:
            prod:
                host: chamados.gtech.site
                user: root
                password: d8hj0ptr
                path: /var/www/html/chamados

pre_deploy:
    - "php -v"
post_deploy:
    - "composer install"
    - "/etc/init.d/httpd restart"

plugins:
    slack:
        hook_uri: "https://hooks.slack.com/services/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"
        messages:                        
            success: "Deploy finalizado com sucesso!"
            failed: "Falha ao realizar deploy!"